### ISSUE TITLE
Setup Read the Docs

### ISSUE THREAD

**Issue by dviererbe** [canonical/ubuntu-packaging-guide#3]
The `main` branch should automatically be deployed to Read the Docs.

This issue tracks this effort.

**Comment by s-makin** [comment]
The docs as a project are now on RTD. 

Next steps:
 - [Diataxis/general tidy up](https://github.com/canonical/ubuntu-packaging-guide/pull/6)
 - Translations

**Comment by dviererbe** [comment]
I think this issue is solved.
