### ISSUE TITLE
State of Licenses

### ISSUE THREAD

**Issue by dviererbe** [canonical/ubuntu-packaging-guide#9]
We have two licenses
- `COPYING` contains a `Attribution-ShareAlike 3.0 Unported` license
- `COPYING.GPL3` contains a `GNU GENERAL PUBLIC LICENSE Version 3` license

1. Why do we have two licenses?
2. Do we still need two licenses?

**Comment by s-makin** [comment]
The question of which license we should use might be one for the community team, I guess? I would have thought it should the same as for any other public Canonical project, but could be worth asking Aaron anyway to see if they have any insight.

**Comment by dviererbe** [comment]
I think I can answer Question 1: the `themes/` folder (we removed with PR #6) was licensed under varies licenses like GPL 2/3/3+, BSD-3 etc. as you can see here https://github.com/canonical/ubuntu-packaging-guide/blob/d8db1b2bbd368bd01fafa7a6cc48c46a125a18e9/copyright
```
Files: *
Copyright: 2010-2017, Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
License: CC-BY-SA-3.0

Files: themes/ubuntu/static/images/background-header-home.png
       themes/ubuntu/static/images/background-footer.png
       themes/ubuntu/static/images/sec-nav-hover.gif
       themes/ubuntu/static/base.css
       themes/ubuntu/static/home.css
Copyright: 2011 Canonical Ltd.
License: GPL-3

Files: themes/ubuntu/layout.html
       themes/ubuntu/searchbox.html
Copyright: 2007-2010, the Sphinx team
           2010-2013, Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
License: BSD-3-clause

Files: themes/ubuntu/static/reset.css
Copyright: 2010, Yahoo! Inc.
License: BSD-3-clause

Files: themes/ubuntu/static/960.css
Copyright: Nathan Smith
License: GPL-3+ or MIT

Files: themes/ubuntu/static/images/go-home.png
       themes/ubuntu/static/images/go-next.png
       themes/ubuntu/static/images/go-previous.png
Copyright: Daniel Fore <Daniel.P.Fore@gmail.com>
           Jonian Guveli <jonian.guveli@gmail.com>
           K.Vishnoo Charan Reddy <vish@ubuntu.com>
```

**Comment by dviererbe** [comment]
I asked Aaron and he said we can just use `CC-BY-SA-3.0`.
